/**
 * Do not edit directly, this file was auto-generated.
 */

export default {
  blue: {
    50: {
      key: "{blue.50}",
      $value: "#eff6ff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#EFF6FF",
        $type: "color",
        key: "{blue.50}",
      },
      name: "Blue50",
      attributes: {
        category: "blue",
        type: "50",
      },
      path: ["blue", "50"],
    },
    100: {
      key: "{blue.100}",
      $value: "#dbeafe",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#DBEAFE",
        $type: "color",
        key: "{blue.100}",
      },
      name: "Blue100",
      attributes: {
        category: "blue",
        type: "100",
      },
      path: ["blue", "100"],
    },
    150: {
      key: "{blue.150}",
      $value: "#d3e5ff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#D3E5FF",
        $type: "color",
        key: "{blue.150}",
      },
      name: "Blue150",
      attributes: {
        category: "blue",
        type: "150",
      },
      path: ["blue", "150"],
    },
    200: {
      key: "{blue.200}",
      $value: "#bfdbfe",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#BFDBFE",
        $type: "color",
        key: "{blue.200}",
      },
      name: "Blue200",
      attributes: {
        category: "blue",
        type: "200",
      },
      path: ["blue", "200"],
    },
    300: {
      key: "{blue.300}",
      $value: "#93c5fd",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#93C5FD",
        $type: "color",
        key: "{blue.300}",
      },
      name: "Blue300",
      attributes: {
        category: "blue",
        type: "300",
      },
      path: ["blue", "300"],
    },
    400: {
      key: "{blue.400}",
      $value: "#60a5fa",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#60A5FA",
        $type: "color",
        key: "{blue.400}",
      },
      name: "Blue400",
      attributes: {
        category: "blue",
        type: "400",
      },
      path: ["blue", "400"],
    },
    500: {
      key: "{blue.500}",
      $value: "#3b82f6",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#3B82F6",
        $type: "color",
        key: "{blue.500}",
      },
      name: "Blue500",
      attributes: {
        category: "blue",
        type: "500",
      },
      path: ["blue", "500"],
    },
    600: {
      key: "{blue.600}",
      $value: "#0061ff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#0061FF",
        $type: "color",
        key: "{blue.600}",
      },
      name: "Blue600",
      attributes: {
        category: "blue",
        type: "600",
      },
      path: ["blue", "600"],
    },
    700: {
      key: "{blue.700}",
      $value: "#004fcc",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#004FCC",
        $type: "color",
        key: "{blue.700}",
      },
      name: "Blue700",
      attributes: {
        category: "blue",
        type: "700",
      },
      path: ["blue", "700"],
    },
    800: {
      key: "{blue.800}",
      $value: "#003a99",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#003A99",
        $type: "color",
        key: "{blue.800}",
      },
      name: "Blue800",
      attributes: {
        category: "blue",
        type: "800",
      },
      path: ["blue", "800"],
    },
  },
  gray: {
    0: {
      key: "{gray.0}",
      $value: "#ffffff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FFFFFF",
        $type: "color",
        key: "{gray.0}",
      },
      name: "Gray0",
      attributes: {
        category: "gray",
        type: "0",
      },
      path: ["gray", "0"],
    },
    50: {
      key: "{gray.50}",
      $value: "#f8f9fb",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#F8F9FB",
        $type: "color",
        key: "{gray.50}",
      },
      name: "Gray50",
      attributes: {
        category: "gray",
        type: "50",
      },
      path: ["gray", "50"],
    },
    100: {
      key: "{gray.100}",
      $value: "#f1f3f5",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#F1F3F5",
        $type: "color",
        key: "{gray.100}",
      },
      name: "Gray100",
      attributes: {
        category: "gray",
        type: "100",
      },
      path: ["gray", "100"],
    },
    200: {
      key: "{gray.200}",
      $value: "#e5e8eb",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#E5E8EB",
        $type: "color",
        key: "{gray.200}",
      },
      name: "Gray200",
      attributes: {
        category: "gray",
        type: "200",
      },
      path: ["gray", "200"],
    },
    300: {
      key: "{gray.300}",
      $value: "#d1d6db",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#D1D6DB",
        $type: "color",
        key: "{gray.300}",
      },
      name: "Gray300",
      attributes: {
        category: "gray",
        type: "300",
      },
      path: ["gray", "300"],
    },
    400: {
      key: "{gray.400}",
      $value: "#b0b8c1",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#B0B8C1",
        $type: "color",
        key: "{gray.400}",
      },
      name: "Gray400",
      attributes: {
        category: "gray",
        type: "400",
      },
      path: ["gray", "400"],
    },
    500: {
      key: "{gray.500}",
      $value: "#8b95a1",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#8B95A1",
        $type: "color",
        key: "{gray.500}",
      },
      name: "Gray500",
      attributes: {
        category: "gray",
        type: "500",
      },
      path: ["gray", "500"],
    },
    600: {
      key: "{gray.600}",
      $value: "#6b7684",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#6B7684",
        $type: "color",
        key: "{gray.600}",
      },
      name: "Gray600",
      attributes: {
        category: "gray",
        type: "600",
      },
      path: ["gray", "600"],
    },
    700: {
      key: "{gray.700}",
      $value: "#4e5968",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#4E5968",
        $type: "color",
        key: "{gray.700}",
      },
      name: "Gray700",
      attributes: {
        category: "gray",
        type: "700",
      },
      path: ["gray", "700"],
    },
    800: {
      key: "{gray.800}",
      $value: "#333d4b",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#333D4B",
        $type: "color",
        key: "{gray.800}",
      },
      name: "Gray800",
      attributes: {
        category: "gray",
        type: "800",
      },
      path: ["gray", "800"],
    },
    900: {
      key: "{gray.900}",
      $value: "#191f28",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#191F28",
        $type: "color",
        key: "{gray.900}",
      },
      name: "Gray900",
      attributes: {
        category: "gray",
        type: "900",
      },
      path: ["gray", "900"],
    },
    1000: {
      key: "{gray.1000}",
      $value: "#000000",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#000000",
        $type: "color",
        key: "{gray.1000}",
      },
      name: "Gray1000",
      attributes: {
        category: "gray",
        type: "1000",
      },
      path: ["gray", "1000"],
    },
  },
  red: {
    50: {
      key: "{red.50}",
      $value: "#fff0f0",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FFF0F0",
        $type: "color",
        key: "{red.50}",
      },
      name: "Red50",
      attributes: {
        category: "red",
        type: "50",
      },
      path: ["red", "50"],
    },
    80: {
      key: "{red.80}",
      $value: "#ffd8d8",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FFD8D8",
        $type: "color",
        key: "{red.80}",
      },
      name: "Red80",
      attributes: {
        category: "red",
        type: "80",
      },
      path: ["red", "80"],
    },
    500: {
      key: "{red.500}",
      $value: "#ef4444",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#EF4444",
        $type: "color",
        key: "{red.500}",
      },
      name: "Red500",
      attributes: {
        category: "red",
        type: "500",
      },
      path: ["red", "500"],
    },
  },
  orange: {
    500: {
      key: "{orange.500}",
      $value: "#f59e0b",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#F59E0B",
        $type: "color",
        key: "{orange.500}",
      },
      name: "Orange500",
      attributes: {
        category: "orange",
        type: "500",
      },
      path: ["orange", "500"],
    },
  },
  green: {
    500: {
      key: "{green.500}",
      $value: "#10b981",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#10B981",
        $type: "color",
        key: "{green.500}",
      },
      name: "Green500",
      attributes: {
        category: "green",
        type: "500",
      },
      path: ["green", "500"],
    },
  },
  yellow: {
    50: {
      key: "{yellow.50}",
      $value: "#fffaeb",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FFFAEB",
        $type: "color",
        key: "{yellow.50}",
      },
      name: "Yellow50",
      attributes: {
        category: "yellow",
        type: "50",
      },
      path: ["yellow", "50"],
    },
    100: {
      key: "{yellow.100}",
      $value: "#fef3c7",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FEF3C7",
        $type: "color",
        key: "{yellow.100}",
      },
      name: "Yellow100",
      attributes: {
        category: "yellow",
        type: "100",
      },
      path: ["yellow", "100"],
    },
    200: {
      key: "{yellow.200}",
      $value: "#fee588",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FEE588",
        $type: "color",
        key: "{yellow.200}",
      },
      name: "Yellow200",
      attributes: {
        category: "yellow",
        type: "200",
      },
      path: ["yellow", "200"],
    },
    300: {
      key: "{yellow.300}",
      $value: "#ffd250",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FFD250",
        $type: "color",
        key: "{yellow.300}",
      },
      name: "Yellow300",
      attributes: {
        category: "yellow",
        type: "300",
      },
      path: ["yellow", "300"],
    },
    400: {
      key: "{yellow.400}",
      $value: "#ffc72c",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FFC72C",
        $type: "color",
        key: "{yellow.400}",
      },
      name: "Yellow400",
      attributes: {
        category: "yellow",
        type: "400",
      },
      path: ["yellow", "400"],
    },
    500: {
      key: "{yellow.500}",
      $value: "#e5a700",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#E5A700",
        $type: "color",
        key: "{yellow.500}",
      },
      name: "Yellow500",
      attributes: {
        category: "yellow",
        type: "500",
      },
      path: ["yellow", "500"],
    },
    600: {
      key: "{yellow.600}",
      $value: "#b58000",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#B58000",
        $type: "color",
        key: "{yellow.600}",
      },
      name: "Yellow600",
      attributes: {
        category: "yellow",
        type: "600",
      },
      path: ["yellow", "600"],
    },
    700: {
      key: "{yellow.700}",
      $value: "#7a5400",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#7A5400",
        $type: "color",
        key: "{yellow.700}",
      },
      name: "Yellow700",
      attributes: {
        category: "yellow",
        type: "700",
      },
      path: ["yellow", "700"],
    },
    800: {
      key: "{yellow.800}",
      $value: "#4a3400",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#4A3400",
        $type: "color",
        key: "{yellow.800}",
      },
      name: "Yellow800",
      attributes: {
        category: "yellow",
        type: "800",
      },
      path: ["yellow", "800"],
    },
  },
  bg: {
    base: {
      key: "{bg.base}",
      $value: "#ffffff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.0}",
        $type: "color",
        key: "{bg.base}",
      },
      name: "BgBase",
      attributes: {
        category: "bg",
        type: "base",
      },
      path: ["bg", "base"],
    },
    subtle: {
      key: "{bg.subtle}",
      $value: "#f8f9fb",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.50}",
        $type: "color",
        key: "{bg.subtle}",
      },
      name: "BgSubtle",
      attributes: {
        category: "bg",
        type: "subtle",
      },
      path: ["bg", "subtle"],
    },
    muted: {
      key: "{bg.muted}",
      $value: "#f1f3f5",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.100}",
        $type: "color",
        key: "{bg.muted}",
      },
      name: "BgMuted",
      attributes: {
        category: "bg",
        type: "muted",
      },
      path: ["bg", "muted"],
    },
    disabled: {
      key: "{bg.disabled}",
      $value: "#e5e8eb",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.200}",
        $type: "color",
        key: "{bg.disabled}",
      },
      name: "BgDisabled",
      attributes: {
        category: "bg",
        type: "disabled",
      },
      path: ["bg", "disabled"],
    },
    brand: {
      key: "{bg.brand}",
      $value: "#eff6ff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{blue.50}",
        $type: "color",
        key: "{bg.brand}",
      },
      name: "BgBrand",
      attributes: {
        category: "bg",
        type: "brand",
      },
      path: ["bg", "brand"],
    },
    warn: {
      key: "{bg.warn}",
      $value: "#fffaeb",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{yellow.50}",
        $type: "color",
        key: "{bg.warn}",
      },
      name: "BgWarn",
      attributes: {
        category: "bg",
        type: "warn",
      },
      path: ["bg", "warn"],
    },
    error: {
      key: "{bg.error}",
      $value: "#fff0f0",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{red.50}",
        $type: "color",
        key: "{bg.error}",
      },
      name: "BgError",
      attributes: {
        category: "bg",
        type: "error",
      },
      path: ["bg", "error"],
    },
    blur: {
      key: "{bg.blur}",
      $value: "#ffffff99",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FFFFFF99",
        $type: "color",
        key: "{bg.blur}",
      },
      name: "BgBlur",
      attributes: {
        category: "bg",
        type: "blur",
      },
      path: ["bg", "blur"],
    },
    dim: {
      key: "{bg.dim}",
      $value: "#00000033",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#00000033",
        $type: "color",
        key: "{bg.dim}",
      },
      name: "BgDim",
      attributes: {
        category: "bg",
        type: "dim",
      },
      path: ["bg", "dim"],
    },
  },
  border: {
    default: {
      key: "{border.default}",
      $value: "#e5e8eb",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.200}",
        $type: "color",
        key: "{border.default}",
      },
      name: "BorderDefault",
      attributes: {
        category: "border",
        type: "default",
      },
      path: ["border", "default"],
    },
    strong: {
      key: "{border.strong}",
      $value: "#d1d6db",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.300}",
        $type: "color",
        key: "{border.strong}",
      },
      name: "BorderStrong",
      attributes: {
        category: "border",
        type: "strong",
      },
      path: ["border", "strong"],
    },
    brand: {
      key: "{border.brand}",
      $value: "#0061ff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{blue.600}",
        $type: "color",
        key: "{border.brand}",
      },
      name: "BorderBrand",
      attributes: {
        category: "border",
        type: "brand",
      },
      path: ["border", "brand"],
    },
    "brand-subtle": {
      key: "{border.brand-subtle}",
      $value: "#d3e5ff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{blue.150}",
        $type: "color",
        key: "{border.brand-subtle}",
      },
      name: "BorderBrandSubtle",
      attributes: {
        category: "border",
        type: "brand-subtle",
      },
      path: ["border", "brand-subtle"],
    },
    error: {
      key: "{border.error}",
      $value: "#ef4444",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{red.500}",
        $type: "color",
        key: "{border.error}",
      },
      name: "BorderError",
      attributes: {
        category: "border",
        type: "error",
      },
      path: ["border", "error"],
    },
    "error-subtle": {
      key: "{border.error-subtle}",
      $value: "#ffd8d8",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{red.80}",
        $type: "color",
        key: "{border.error-subtle}",
      },
      name: "BorderErrorSubtle",
      attributes: {
        category: "border",
        type: "error-subtle",
      },
      path: ["border", "error-subtle"],
    },
    warn: {
      key: "{border.warn}",
      $value: "#fee588",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{yellow.200}",
        $type: "color",
        key: "{border.warn}",
      },
      name: "BorderWarn",
      attributes: {
        category: "border",
        type: "warn",
      },
      path: ["border", "warn"],
    },
    "warn-subtle": {
      key: "{border.warn-subtle}",
      $value: "#fef3c7",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{yellow.100}",
        $type: "color",
        key: "{border.warn-subtle}",
      },
      name: "BorderWarnSubtle",
      attributes: {
        category: "border",
        type: "warn-subtle",
      },
      path: ["border", "warn-subtle"],
    },
    "warn-strong": {
      key: "{border.warn-strong}",
      $value: "#ffc72c",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{yellow.400}",
        $type: "color",
        key: "{border.warn-strong}",
      },
      name: "BorderWarnStrong",
      attributes: {
        category: "border",
        type: "warn-strong",
      },
      path: ["border", "warn-strong"],
    },
    success: {
      key: "{border.success}",
      $value: "#10b981",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{green.500}",
        $type: "color",
        key: "{border.success}",
      },
      name: "BorderSuccess",
      attributes: {
        category: "border",
        type: "success",
      },
      path: ["border", "success"],
    },
  },
  text: {
    primary: {
      key: "{text.primary}",
      $value: "#191f28",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.900}",
        $type: "color",
        key: "{text.primary}",
      },
      name: "TextPrimary",
      attributes: {
        category: "text",
        type: "primary",
      },
      path: ["text", "primary"],
    },
    secondary: {
      key: "{text.secondary}",
      $value: "#333d4b",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.800}",
        $type: "color",
        key: "{text.secondary}",
      },
      name: "TextSecondary",
      attributes: {
        category: "text",
        type: "secondary",
      },
      path: ["text", "secondary"],
    },
    tertiary: {
      key: "{text.tertiary}",
      $value: "#8b95a1",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.500}",
        $type: "color",
        key: "{text.tertiary}",
      },
      name: "TextTertiary",
      attributes: {
        category: "text",
        type: "tertiary",
      },
      path: ["text", "tertiary"],
    },
    disabled: {
      key: "{text.disabled}",
      $value: "#b0b8c1",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.400}",
        $type: "color",
        key: "{text.disabled}",
      },
      name: "TextDisabled",
      attributes: {
        category: "text",
        type: "disabled",
      },
      path: ["text", "disabled"],
    },
    inverse: {
      key: "{text.inverse}",
      $value: "#ffffff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.0}",
        $type: "color",
        key: "{text.inverse}",
      },
      name: "TextInverse",
      attributes: {
        category: "text",
        type: "inverse",
      },
      path: ["text", "inverse"],
    },
    brand: {
      key: "{text.brand}",
      $value: "#0061ff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{blue.600}",
        $type: "color",
        key: "{text.brand}",
      },
      name: "TextBrand",
      attributes: {
        category: "text",
        type: "brand",
      },
      path: ["text", "brand"],
    },
    error: {
      key: "{text.error}",
      $value: "#ef4444",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{red.500}",
        $type: "color",
        key: "{text.error}",
      },
      name: "TextError",
      attributes: {
        category: "text",
        type: "error",
      },
      path: ["text", "error"],
    },
    warn: {
      key: "{text.warn}",
      $value: "#b58000",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{yellow.600}",
        $type: "color",
        key: "{text.warn}",
      },
      name: "TextWarn",
      attributes: {
        category: "text",
        type: "warn",
      },
      path: ["text", "warn"],
    },
  },
  interactive: {
    primary: {
      key: "{interactive.primary}",
      $value: "#3b82f6",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{blue.500}",
        $type: "color",
        key: "{interactive.primary}",
      },
      name: "InteractivePrimary",
      attributes: {
        category: "interactive",
        type: "primary",
      },
      path: ["interactive", "primary"],
    },
    "primary-hover": {
      key: "{interactive.primary-hover}",
      $value: "#60a5fa",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{blue.400}",
        $type: "color",
        key: "{interactive.primary-hover}",
      },
      name: "InteractivePrimaryHover",
      attributes: {
        category: "interactive",
        type: "primary-hover",
      },
      path: ["interactive", "primary-hover"],
    },
    "primary-pressed": {
      key: "{interactive.primary-pressed}",
      $value: "#0061ff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{blue.600}",
        $type: "color",
        key: "{interactive.primary-pressed}",
      },
      name: "InteractivePrimaryPressed",
      attributes: {
        category: "interactive",
        type: "primary-pressed",
      },
      path: ["interactive", "primary-pressed"],
    },
    "primary-disabled": {
      key: "{interactive.primary-disabled}",
      $value: "#e5e8eb",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{gray.200}",
        $type: "color",
        key: "{interactive.primary-disabled}",
      },
      name: "InteractivePrimaryDisabled",
      attributes: {
        category: "interactive",
        type: "primary-disabled",
      },
      path: ["interactive", "primary-disabled"],
    },
  },
  branding: {
    "appcenter-brand": {
      key: "{branding.appcenter-brand}",
      $value: "#57ff85",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#57FF85",
        $type: "color",
        key: "{branding.appcenter-brand}",
      },
      name: "BrandingAppcenterBrand",
      attributes: {
        category: "branding",
        type: "appcenter-brand",
      },
      path: ["branding", "appcenter-brand"],
    },
    "brand-blue": {
      key: "{branding.brand-blue}",
      $value: "#0061ff",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{blue.600}",
        $type: "color",
        key: "{branding.brand-blue}",
      },
      name: "BrandingBrandBlue",
      attributes: {
        category: "branding",
        type: "brand-blue",
      },
      path: ["branding", "brand-blue"],
    },
    "brand-yellow": {
      key: "{branding.brand-yellow}",
      $value: "#ffc72c",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "{yellow.400}",
        $type: "color",
        key: "{branding.brand-yellow}",
      },
      name: "BrandingBrandYellow",
      attributes: {
        category: "branding",
        type: "brand-yellow",
      },
      path: ["branding", "brand-yellow"],
    },
  },
  "timeTable-color": {
    red: {
      key: "{timeTable-color.red}",
      $value: "#ffa6a6",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FFA6A6",
        $type: "color",
        key: "{timeTable-color.red}",
      },
      name: "TimeTableColorRed",
      attributes: {
        category: "timeTable-color",
        type: "red",
      },
      path: ["timeTable-color", "red"],
    },
    orange: {
      key: "{timeTable-color.orange}",
      $value: "#ffcb94",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FFCB94",
        $type: "color",
        key: "{timeTable-color.orange}",
      },
      name: "TimeTableColorOrange",
      attributes: {
        category: "timeTable-color",
        type: "orange",
      },
      path: ["timeTable-color", "orange"],
    },
    yellow: {
      key: "{timeTable-color.yellow}",
      $value: "#ffe589",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FFE589",
        $type: "color",
        key: "{timeTable-color.yellow}",
      },
      name: "TimeTableColorYellow",
      attributes: {
        category: "timeTable-color",
        type: "yellow",
      },
      path: ["timeTable-color", "yellow"],
    },
    lightgreen: {
      key: "{timeTable-color.lightgreen}",
      $value: "#8ce99a",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#8CE99A",
        $type: "color",
        key: "{timeTable-color.lightgreen}",
      },
      name: "TimeTableColorLightgreen",
      attributes: {
        category: "timeTable-color",
        type: "lightgreen",
      },
      path: ["timeTable-color", "lightgreen"],
    },
    teal: {
      key: "{timeTable-color.teal}",
      $value: "#79dddf",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#79DDDF",
        $type: "color",
        key: "{timeTable-color.teal}",
      },
      name: "TimeTableColorTeal",
      attributes: {
        category: "timeTable-color",
        type: "teal",
      },
      path: ["timeTable-color", "teal"],
    },
    skyblue: {
      key: "{timeTable-color.skyblue}",
      $value: "#94cdfa",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#94CDFA",
        $type: "color",
        key: "{timeTable-color.skyblue}",
      },
      name: "TimeTableColorSkyblue",
      attributes: {
        category: "timeTable-color",
        type: "skyblue",
      },
      path: ["timeTable-color", "skyblue"],
    },
    lilac: {
      key: "{timeTable-color.lilac}",
      $value: "#acbcfd",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#ACBCFD",
        $type: "color",
        key: "{timeTable-color.lilac}",
      },
      name: "TimeTableColorLilac",
      attributes: {
        category: "timeTable-color",
        type: "lilac",
      },
      path: ["timeTable-color", "lilac"],
    },
    violet: {
      key: "{timeTable-color.violet}",
      $value: "#c1acfc",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#C1ACFC",
        $type: "color",
        key: "{timeTable-color.violet}",
      },
      name: "TimeTableColorViolet",
      attributes: {
        category: "timeTable-color",
        type: "violet",
      },
      path: ["timeTable-color", "violet"],
    },
    purple: {
      key: "{timeTable-color.purple}",
      $value: "#e9adf7",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#E9ADF7",
        $type: "color",
        key: "{timeTable-color.purple}",
      },
      name: "TimeTableColorPurple",
      attributes: {
        category: "timeTable-color",
        type: "purple",
      },
      path: ["timeTable-color", "purple"],
    },
    pink: {
      key: "{timeTable-color.pink}",
      $value: "#fab5cd",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#FAB5CD",
        $type: "color",
        key: "{timeTable-color.pink}",
      },
      name: "TimeTableColorPink",
      attributes: {
        category: "timeTable-color",
        type: "pink",
      },
      path: ["timeTable-color", "pink"],
    },
    gray: {
      key: "{timeTable-color.gray}",
      $value: "#ced3d7",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#CED3D7",
        $type: "color",
        key: "{timeTable-color.gray}",
      },
      name: "TimeTableColorGray",
      attributes: {
        category: "timeTable-color",
        type: "gray",
      },
      path: ["timeTable-color", "gray"],
    },
    "available-time": {
      key: "{timeTable-color.available-time}",
      $value: "#3b82f633",
      $type: "color",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: "#3B82F633",
        $type: "color",
        key: "{timeTable-color.available-time}",
      },
      name: "TimeTableColorAvailableTime",
      attributes: {
        category: "timeTable-color",
        type: "available-time",
      },
      path: ["timeTable-color", "available-time"],
    },
  },
  space: {
    1: {
      key: "{space.1}",
      $value: 4,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 4,
        $type: "number",
        key: "{space.1}",
      },
      name: "Space1",
      attributes: {
        category: "space",
        type: "1",
      },
      path: ["space", "1"],
    },
    2: {
      key: "{space.2}",
      $value: 8,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 8,
        $type: "number",
        key: "{space.2}",
      },
      name: "Space2",
      attributes: {
        category: "space",
        type: "2",
      },
      path: ["space", "2"],
    },
    3: {
      key: "{space.3}",
      $value: 12,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 12,
        $type: "number",
        key: "{space.3}",
      },
      name: "Space3",
      attributes: {
        category: "space",
        type: "3",
      },
      path: ["space", "3"],
    },
    4: {
      key: "{space.4}",
      $value: 16,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 16,
        $type: "number",
        key: "{space.4}",
      },
      name: "Space4",
      attributes: {
        category: "space",
        type: "4",
      },
      path: ["space", "4"],
    },
    5: {
      key: "{space.5}",
      $value: 20,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 20,
        $type: "number",
        key: "{space.5}",
      },
      name: "Space5",
      attributes: {
        category: "space",
        type: "5",
      },
      path: ["space", "5"],
    },
    6: {
      key: "{space.6}",
      $value: 24,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 24,
        $type: "number",
        key: "{space.6}",
      },
      name: "Space6",
      attributes: {
        category: "space",
        type: "6",
      },
      path: ["space", "6"],
    },
    8: {
      key: "{space.8}",
      $value: 32,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 32,
        $type: "number",
        key: "{space.8}",
      },
      name: "Space8",
      attributes: {
        category: "space",
        type: "8",
      },
      path: ["space", "8"],
    },
  },
  radius: {
    sm: {
      key: "{radius.sm}",
      $value: 8,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 8,
        $type: "number",
        key: "{radius.sm}",
      },
      name: "RadiusSm",
      attributes: {
        category: "radius",
        type: "sm",
      },
      path: ["radius", "sm"],
    },
    md: {
      key: "{radius.md}",
      $value: 12,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 12,
        $type: "number",
        key: "{radius.md}",
      },
      name: "RadiusMd",
      attributes: {
        category: "radius",
        type: "md",
      },
      path: ["radius", "md"],
    },
    lg: {
      key: "{radius.lg}",
      $value: 16,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 16,
        $type: "number",
        key: "{radius.lg}",
      },
      name: "RadiusLg",
      attributes: {
        category: "radius",
        type: "lg",
      },
      path: ["radius", "lg"],
    },
    xl: {
      key: "{radius.xl}",
      $value: 24,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 24,
        $type: "number",
        key: "{radius.xl}",
      },
      name: "RadiusXl",
      attributes: {
        category: "radius",
        type: "xl",
      },
      path: ["radius", "xl"],
    },
    "2xl": {
      key: "{radius.2xl}",
      $value: 32,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 32,
        $type: "number",
        key: "{radius.2xl}",
      },
      name: "Radius2xl",
      attributes: {
        category: "radius",
        type: "2xl",
      },
      path: ["radius", "2xl"],
    },
    full: {
      key: "{radius.full}",
      $value: 999,
      $type: "number",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: 999,
        $type: "number",
        key: "{radius.full}",
      },
      name: "RadiusFull",
      attributes: {
        category: "radius",
        type: "full",
      },
      path: ["radius", "full"],
    },
  },
  tt: {
    "color-0": {
      bg: {
        key: "{tt.color-0.bg}",
        $value: "#2e2e2e",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#2E2E2E",
          $type: "color",
          key: "{tt.color-0.bg}",
        },
        name: "TtColor0Bg",
        attributes: {
          category: "tt",
          type: "color-0",
          item: "bg",
        },
        path: ["tt", "color-0", "bg"],
      },
      text: {
        key: "{tt.color-0.text}",
        $value: "#ffffff",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#FFFFFF",
          $type: "color",
          key: "{tt.color-0.text}",
        },
        name: "TtColor0Text",
        attributes: {
          category: "tt",
          type: "color-0",
          item: "text",
        },
        path: ["tt", "color-0", "text"],
      },
    },
    "color-1": {
      bg: {
        key: "{tt.color-1.bg}",
        $value: "#454545",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#454545",
          $type: "color",
          key: "{tt.color-1.bg}",
        },
        name: "TtColor1Bg",
        attributes: {
          category: "tt",
          type: "color-1",
          item: "bg",
        },
        path: ["tt", "color-1", "bg"],
      },
      text: {
        key: "{tt.color-1.text}",
        $value: "#ffffff",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#FFFFFF",
          $type: "color",
          key: "{tt.color-1.text}",
        },
        name: "TtColor1Text",
        attributes: {
          category: "tt",
          type: "color-1",
          item: "text",
        },
        path: ["tt", "color-1", "text"],
      },
    },
    "color-2": {
      bg: {
        key: "{tt.color-2.bg}",
        $value: "#5c5c5c",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#5C5C5C",
          $type: "color",
          key: "{tt.color-2.bg}",
        },
        name: "TtColor2Bg",
        attributes: {
          category: "tt",
          type: "color-2",
          item: "bg",
        },
        path: ["tt", "color-2", "bg"],
      },
      text: {
        key: "{tt.color-2.text}",
        $value: "#ffffff",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#FFFFFF",
          $type: "color",
          key: "{tt.color-2.text}",
        },
        name: "TtColor2Text",
        attributes: {
          category: "tt",
          type: "color-2",
          item: "text",
        },
        path: ["tt", "color-2", "text"],
      },
    },
    "color-3": {
      bg: {
        key: "{tt.color-3.bg}",
        $value: "#737373",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#737373",
          $type: "color",
          key: "{tt.color-3.bg}",
        },
        name: "TtColor3Bg",
        attributes: {
          category: "tt",
          type: "color-3",
          item: "bg",
        },
        path: ["tt", "color-3", "bg"],
      },
      text: {
        key: "{tt.color-3.text}",
        $value: "#ffffff",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#FFFFFF",
          $type: "color",
          key: "{tt.color-3.text}",
        },
        name: "TtColor3Text",
        attributes: {
          category: "tt",
          type: "color-3",
          item: "text",
        },
        path: ["tt", "color-3", "text"],
      },
    },
    "color-4": {
      bg: {
        key: "{tt.color-4.bg}",
        $value: "#7a7a7a",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#7A7A7A",
          $type: "color",
          key: "{tt.color-4.bg}",
        },
        name: "TtColor4Bg",
        attributes: {
          category: "tt",
          type: "color-4",
          item: "bg",
        },
        path: ["tt", "color-4", "bg"],
      },
      text: {
        key: "{tt.color-4.text}",
        $value: "#ffffff",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#FFFFFF",
          $type: "color",
          key: "{tt.color-4.text}",
        },
        name: "TtColor4Text",
        attributes: {
          category: "tt",
          type: "color-4",
          item: "text",
        },
        path: ["tt", "color-4", "text"],
      },
    },
    "color-5": {
      bg: {
        key: "{tt.color-5.bg}",
        $value: "#a1a1a1",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#A1A1A1",
          $type: "color",
          key: "{tt.color-5.bg}",
        },
        name: "TtColor5Bg",
        attributes: {
          category: "tt",
          type: "color-5",
          item: "bg",
        },
        path: ["tt", "color-5", "bg"],
      },
      text: {
        key: "{tt.color-5.text}",
        $value: "#191f28",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#191F28",
          $type: "color",
          key: "{tt.color-5.text}",
        },
        name: "TtColor5Text",
        attributes: {
          category: "tt",
          type: "color-5",
          item: "text",
        },
        path: ["tt", "color-5", "text"],
      },
    },
    "color-6": {
      bg: {
        key: "{tt.color-6.bg}",
        $value: "#b8b8b8",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#B8B8B8",
          $type: "color",
          key: "{tt.color-6.bg}",
        },
        name: "TtColor6Bg",
        attributes: {
          category: "tt",
          type: "color-6",
          item: "bg",
        },
        path: ["tt", "color-6", "bg"],
      },
      text: {
        key: "{tt.color-6.text}",
        $value: "#191f28",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#191F28",
          $type: "color",
          key: "{tt.color-6.text}",
        },
        name: "TtColor6Text",
        attributes: {
          category: "tt",
          type: "color-6",
          item: "text",
        },
        path: ["tt", "color-6", "text"],
      },
    },
    "color-7": {
      bg: {
        key: "{tt.color-7.bg}",
        $value: "#cfcfcf",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#CFCFCF",
          $type: "color",
          key: "{tt.color-7.bg}",
        },
        name: "TtColor7Bg",
        attributes: {
          category: "tt",
          type: "color-7",
          item: "bg",
        },
        path: ["tt", "color-7", "bg"],
      },
      text: {
        key: "{tt.color-7.text}",
        $value: "#191f28",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#191F28",
          $type: "color",
          key: "{tt.color-7.text}",
        },
        name: "TtColor7Text",
        attributes: {
          category: "tt",
          type: "color-7",
          item: "text",
        },
        path: ["tt", "color-7", "text"],
      },
    },
    "color-8": {
      bg: {
        key: "{tt.color-8.bg}",
        $value: "#e0e0e0",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#E0E0E0",
          $type: "color",
          key: "{tt.color-8.bg}",
        },
        name: "TtColor8Bg",
        attributes: {
          category: "tt",
          type: "color-8",
          item: "bg",
        },
        path: ["tt", "color-8", "bg"],
      },
      text: {
        key: "{tt.color-8.text}",
        $value: "#191f28",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#191F28",
          $type: "color",
          key: "{tt.color-8.text}",
        },
        name: "TtColor8Text",
        attributes: {
          category: "tt",
          type: "color-8",
          item: "text",
        },
        path: ["tt", "color-8", "text"],
      },
    },
    "color-9": {
      bg: {
        key: "{tt.color-9.bg}",
        $value: "#ededed",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#EDEDED",
          $type: "color",
          key: "{tt.color-9.bg}",
        },
        name: "TtColor9Bg",
        attributes: {
          category: "tt",
          type: "color-9",
          item: "bg",
        },
        path: ["tt", "color-9", "bg"],
      },
      text: {
        key: "{tt.color-9.text}",
        $value: "#191f28",
        $type: "color",
        filePath: "tokens/tokens.json",
        isSource: true,
        original: {
          $value: "#191F28",
          $type: "color",
          key: "{tt.color-9.text}",
        },
        name: "TtColor9Text",
        attributes: {
          category: "tt",
          type: "color-9",
          item: "text",
        },
        path: ["tt", "color-9", "text"],
      },
    },
  },
  display: {
    key: "{display}",
    $value: {
      fontSize: 32,
      fontFamily: "Pretendard",
      fontWeight: "Bold",
      lineHeight: 40,
      lineHeightUnit: "PIXELS",
      letterSpacing: 0,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 32,
        fontFamily: "Pretendard",
        fontWeight: "Bold",
        lineHeight: 40,
        lineHeightUnit: "PIXELS",
        letterSpacing: 0,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{display}",
    },
    name: "Display",
    attributes: {
      category: "display",
    },
    path: ["display"],
  },
  "title-1": {
    key: "{title-1}",
    $value: {
      fontSize: 24,
      fontFamily: "Pretendard",
      fontWeight: "Bold",
      lineHeight: 32,
      lineHeightUnit: "PIXELS",
      letterSpacing: -0.20000000298023224,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 24,
        fontFamily: "Pretendard",
        fontWeight: "Bold",
        lineHeight: 32,
        lineHeightUnit: "PIXELS",
        letterSpacing: -0.20000000298023224,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{title-1}",
    },
    name: "Title1",
    attributes: {
      category: "title-1",
    },
    path: ["title-1"],
  },
  "title-2": {
    key: "{title-2}",
    $value: {
      fontSize: 20,
      fontFamily: "Pretendard",
      fontWeight: "Bold",
      lineHeight: 28,
      lineHeightUnit: "PIXELS",
      letterSpacing: -0.20000000298023224,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 20,
        fontFamily: "Pretendard",
        fontWeight: "Bold",
        lineHeight: 28,
        lineHeightUnit: "PIXELS",
        letterSpacing: -0.20000000298023224,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{title-2}",
    },
    name: "Title2",
    attributes: {
      category: "title-2",
    },
    path: ["title-2"],
  },
  "title-3": {
    key: "{title-3}",
    $value: {
      fontSize: 16,
      fontFamily: "Pretendard",
      fontWeight: "Bold",
      lineHeight: 24,
      lineHeightUnit: "PIXELS",
      letterSpacing: -0.20000000298023224,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 16,
        fontFamily: "Pretendard",
        fontWeight: "Bold",
        lineHeight: 24,
        lineHeightUnit: "PIXELS",
        letterSpacing: -0.20000000298023224,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{title-3}",
    },
    name: "Title3",
    attributes: {
      category: "title-3",
    },
    path: ["title-3"],
  },
  "title-4": {
    key: "{title-4}",
    $value: {
      fontSize: 14,
      fontFamily: "Pretendard",
      fontWeight: "Bold",
      lineHeight: 24,
      lineHeightUnit: "PIXELS",
      letterSpacing: -0.20000000298023224,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 14,
        fontFamily: "Pretendard",
        fontWeight: "Bold",
        lineHeight: 24,
        lineHeightUnit: "PIXELS",
        letterSpacing: -0.20000000298023224,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{title-4}",
    },
    name: "Title4",
    attributes: {
      category: "title-4",
    },
    path: ["title-4"],
  },
  "heading-1": {
    key: "{heading-1}",
    $value: {
      fontSize: 20,
      fontFamily: "Pretendard",
      fontWeight: "SemiBold",
      lineHeight: 32,
      lineHeightUnit: "PIXELS",
      letterSpacing: 0,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 20,
        fontFamily: "Pretendard",
        fontWeight: "SemiBold",
        lineHeight: 32,
        lineHeightUnit: "PIXELS",
        letterSpacing: 0,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{heading-1}",
    },
    name: "Heading1",
    attributes: {
      category: "heading-1",
    },
    path: ["heading-1"],
  },
  "heading-2": {
    key: "{heading-2}",
    $value: {
      fontSize: 16,
      fontFamily: "Pretendard",
      fontWeight: "SemiBold",
      lineHeight: 24,
      lineHeightUnit: "PIXELS",
      letterSpacing: 0,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 16,
        fontFamily: "Pretendard",
        fontWeight: "SemiBold",
        lineHeight: 24,
        lineHeightUnit: "PIXELS",
        letterSpacing: 0,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{heading-2}",
    },
    name: "Heading2",
    attributes: {
      category: "heading-2",
    },
    path: ["heading-2"],
  },
  "body-1": {
    key: "{body-1}",
    $value: {
      fontSize: 16,
      fontFamily: "Pretendard",
      fontWeight: "Regular",
      lineHeight: 160.0000023841858,
      lineHeightUnit: "PERCENT",
      letterSpacing: 0,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 16,
        fontFamily: "Pretendard",
        fontWeight: "Regular",
        lineHeight: 160.0000023841858,
        lineHeightUnit: "PERCENT",
        letterSpacing: 0,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{body-1}",
    },
    name: "Body1",
    attributes: {
      category: "body-1",
    },
    path: ["body-1"],
  },
  "body-2": {
    key: "{body-2}",
    $value: {
      fontSize: 14,
      fontFamily: "Pretendard",
      fontWeight: "Regular",
      lineHeight: 160.0000023841858,
      lineHeightUnit: "PERCENT",
      letterSpacing: 0,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 14,
        fontFamily: "Pretendard",
        fontWeight: "Regular",
        lineHeight: 160.0000023841858,
        lineHeightUnit: "PERCENT",
        letterSpacing: 0,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{body-2}",
    },
    name: "Body2",
    attributes: {
      category: "body-2",
    },
    path: ["body-2"],
  },
  "label-1": {
    key: "{label-1}",
    $value: {
      fontSize: 16,
      fontFamily: "Pretendard",
      fontWeight: "Medium",
      lineHeight: 24,
      lineHeightUnit: "PIXELS",
      letterSpacing: 0,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 16,
        fontFamily: "Pretendard",
        fontWeight: "Medium",
        lineHeight: 24,
        lineHeightUnit: "PIXELS",
        letterSpacing: 0,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{label-1}",
    },
    name: "Label1",
    attributes: {
      category: "label-1",
    },
    path: ["label-1"],
  },
  "label-2": {
    key: "{label-2}",
    $value: {
      fontSize: 14,
      fontFamily: "Pretendard",
      fontWeight: "Medium",
      lineHeight: 20,
      lineHeightUnit: "PIXELS",
      letterSpacing: 0,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 14,
        fontFamily: "Pretendard",
        fontWeight: "Medium",
        lineHeight: 20,
        lineHeightUnit: "PIXELS",
        letterSpacing: 0,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{label-2}",
    },
    name: "Label2",
    attributes: {
      category: "label-2",
    },
    path: ["label-2"],
  },
  "label-3": {
    key: "{label-3}",
    $value: {
      fontSize: 12,
      fontFamily: "Pretendard",
      fontWeight: "Medium",
      lineHeight: 16,
      lineHeightUnit: "PIXELS",
      letterSpacing: 0,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 12,
        fontFamily: "Pretendard",
        fontWeight: "Medium",
        lineHeight: 16,
        lineHeightUnit: "PIXELS",
        letterSpacing: 0,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{label-3}",
    },
    name: "Label3",
    attributes: {
      category: "label-3",
    },
    path: ["label-3"],
  },
  "caption-1": {
    key: "{caption-1}",
    $value: {
      fontSize: 12,
      fontFamily: "Pretendard",
      fontWeight: "Regular",
      lineHeight: 16,
      lineHeightUnit: "PIXELS",
      letterSpacing: 0,
      letterSpacingUnit: "PIXELS",
      textCase: "ORIGINAL",
      textDecoration: "NONE",
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        fontSize: 12,
        fontFamily: "Pretendard",
        fontWeight: "Regular",
        lineHeight: 16,
        lineHeightUnit: "PIXELS",
        letterSpacing: 0,
        letterSpacingUnit: "PIXELS",
        textCase: "ORIGINAL",
        textDecoration: "NONE",
      },
      $type: "string",
      key: "{caption-1}",
    },
    name: "Caption1",
    attributes: {
      category: "caption-1",
    },
    path: ["caption-1"],
  },
  Bottom_Sheet: {
    key: "{Bottom_Sheet}",
    $value: {
      effects: [
        {
          type: "DROP_SHADOW",
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 0.25,
          },
          offset: {
            x: 0,
            y: 4,
          },
          radius: 24,
          spread: 0,
        },
      ],
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        effects: [
          {
            type: "DROP_SHADOW",
            color: {
              r: 0,
              g: 0,
              b: 0,
              a: 0.25,
            },
            offset: {
              x: 0,
              y: 4,
            },
            radius: 24,
            spread: 0,
          },
        ],
      },
      $type: "string",
      key: "{Bottom_Sheet}",
    },
    name: "BottomSheet",
    attributes: {
      category: "Bottom_Sheet",
    },
    path: ["Bottom_Sheet"],
  },
  Floating_Button: {
    key: "{Floating_Button}",
    $value: {
      effects: [
        {
          type: "DROP_SHADOW",
          color: {
            r: 0,
            g: 0,
            b: 0,
            a: 0.08,
          },
          offset: {
            x: 0,
            y: 4,
          },
          radius: 12,
          spread: 0,
        },
        {
          type: "BACKGROUND_BLUR",
          radius: 20,
        },
      ],
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        effects: [
          {
            type: "DROP_SHADOW",
            color: {
              r: 0,
              g: 0,
              b: 0,
              a: 0.08,
            },
            offset: {
              x: 0,
              y: 4,
            },
            radius: 12,
            spread: 0,
          },
          {
            type: "BACKGROUND_BLUR",
            radius: 20,
          },
        ],
      },
      $type: "string",
      key: "{Floating_Button}",
    },
    name: "FloatingButton",
    attributes: {
      category: "Floating_Button",
    },
    path: ["Floating_Button"],
  },
  Dim: {
    key: "{Dim}",
    $value: {
      effects: [
        {
          type: "BACKGROUND_BLUR",
          radius: 4,
        },
      ],
    },
    $type: "string",
    filePath: "tokens/tokens.json",
    isSource: true,
    original: {
      $value: {
        effects: [
          {
            type: "BACKGROUND_BLUR",
            radius: 4,
          },
        ],
      },
      $type: "string",
      key: "{Dim}",
    },
    name: "Dim",
    attributes: {
      category: "Dim",
    },
    path: ["Dim"],
  },
  elevation: {
    1: {
      key: "{elevation.1}",
      $value: {
        effects: [
          {
            type: "DROP_SHADOW",
            color: {
              r: 0,
              g: 0,
              b: 0,
              a: 0.08,
            },
            offset: {
              x: 0,
              y: 4,
            },
            radius: 12,
            spread: 0,
          },
        ],
      },
      $type: "string",
      filePath: "tokens/tokens.json",
      isSource: true,
      original: {
        $value: {
          effects: [
            {
              type: "DROP_SHADOW",
              color: {
                r: 0,
                g: 0,
                b: 0,
                a: 0.08,
              },
              offset: {
                x: 0,
                y: 4,
              },
              radius: 12,
              spread: 0,
            },
          ],
        },
        $type: "string",
        key: "{elevation.1}",
      },
      name: "Elevation1",
      attributes: {
        category: "elevation",
        type: "1",
      },
      path: ["elevation", "1"],
    },
  },
};
