/**
 * Do not edit directly — generated by scripts/build-tokens.mjs from tokens/ (Figma Tokens Studio).
 * CSS 에서는 src/styles/variables.css 의 var(--...) 를 쓰고, 이 모듈은 JS 에서 실제 값이 필요할 때만 쓴다.
 */

export type TimetableThemeKey = "default" | "pastelWarm" | "pastelCool" | "monotone";

export interface TimetableColor {
  bg: string;
  text: string;
}

export const timetableThemes: Record<TimetableThemeKey, readonly TimetableColor[]> = {
  "default": [
    {
      "bg": "#ffa6a6",
      "text": "#191f28"
    },
    {
      "bg": "#ffcb94",
      "text": "#191f28"
    },
    {
      "bg": "#ffe589",
      "text": "#191f28"
    },
    {
      "bg": "#8ce99a",
      "text": "#191f28"
    },
    {
      "bg": "#79dddf",
      "text": "#191f28"
    },
    {
      "bg": "#94cdfa",
      "text": "#191f28"
    },
    {
      "bg": "#acbcfd",
      "text": "#191f28"
    },
    {
      "bg": "#c1acfc",
      "text": "#191f28"
    },
    {
      "bg": "#e9adf7",
      "text": "#191f28"
    },
    {
      "bg": "#8fa8d9",
      "text": "#191f28"
    }
  ],
  "pastelWarm": [
    {
      "bg": "#ffd9d9",
      "text": "#191f28"
    },
    {
      "bg": "#ffe6cc",
      "text": "#191f28"
    },
    {
      "bg": "#fff4cc",
      "text": "#191f28"
    },
    {
      "bg": "#f0ebcf",
      "text": "#191f28"
    },
    {
      "bg": "#f5dcc9",
      "text": "#191f28"
    },
    {
      "bg": "#f2d9d0",
      "text": "#191f28"
    },
    {
      "bg": "#f5dce0",
      "text": "#191f28"
    },
    {
      "bg": "#f2d9ee",
      "text": "#191f28"
    },
    {
      "bg": "#ebdce6",
      "text": "#191f28"
    },
    {
      "bg": "#e4e0d8",
      "text": "#191f28"
    }
  ],
  "pastelCool": [
    {
      "bg": "#d6e4fa",
      "text": "#191f28"
    },
    {
      "bg": "#d0e7f7",
      "text": "#191f28"
    },
    {
      "bg": "#ccecf2",
      "text": "#191f28"
    },
    {
      "bg": "#ccf0ea",
      "text": "#191f28"
    },
    {
      "bg": "#cff0e0",
      "text": "#191f28"
    },
    {
      "bg": "#d5f0d5",
      "text": "#191f28"
    },
    {
      "bg": "#ddd9f5",
      "text": "#191f28"
    },
    {
      "bg": "#d9def7",
      "text": "#191f28"
    },
    {
      "bg": "#e0dcf2",
      "text": "#191f28"
    },
    {
      "bg": "#e8e4f5",
      "text": "#191f28"
    }
  ],
  "monotone": [
    {
      "bg": "#2e2e2e",
      "text": "#ffffff"
    },
    {
      "bg": "#454545",
      "text": "#ffffff"
    },
    {
      "bg": "#5c5c5c",
      "text": "#ffffff"
    },
    {
      "bg": "#737373",
      "text": "#ffffff"
    },
    {
      "bg": "#7a7a7a",
      "text": "#ffffff"
    },
    {
      "bg": "#a1a1a1",
      "text": "#191f28"
    },
    {
      "bg": "#b8b8b8",
      "text": "#191f28"
    },
    {
      "bg": "#cfcfcf",
      "text": "#191f28"
    },
    {
      "bg": "#e0e0e0",
      "text": "#191f28"
    },
    {
      "bg": "#ededed",
      "text": "#191f28"
    }
  ]
};

export const shadows = {
  "bottomSheet": "0 4px 24px 0 #00000040",
  "elevation1": "0 4px 12px 0 #00000014"
} as const;

export const typography = {
  "display": {
    "fontWeight": "700",
    "lineHeight": "40px",
    "fontSize": "32px",
    "letterSpacing": "0"
  },
  "title1": {
    "fontWeight": "700",
    "lineHeight": "32px",
    "fontSize": "24px",
    "letterSpacing": "-0.2px"
  },
  "title2": {
    "fontWeight": "700",
    "lineHeight": "28px",
    "fontSize": "20px",
    "letterSpacing": "-0.2px"
  },
  "title3": {
    "fontWeight": "700",
    "lineHeight": "24px",
    "fontSize": "16px",
    "letterSpacing": "-0.2px"
  },
  "title4": {
    "fontWeight": "700",
    "lineHeight": "24px",
    "fontSize": "14px",
    "letterSpacing": "-0.2px"
  },
  "heading1": {
    "fontWeight": "600",
    "lineHeight": "32px",
    "fontSize": "20px",
    "letterSpacing": "0"
  },
  "heading2": {
    "fontWeight": "600",
    "lineHeight": "24px",
    "fontSize": "16px",
    "letterSpacing": "0"
  },
  "body1": {
    "fontWeight": "400",
    "lineHeight": 1.6,
    "fontSize": "16px",
    "letterSpacing": "0"
  },
  "body2": {
    "fontWeight": "400",
    "lineHeight": 1.6,
    "fontSize": "14px",
    "letterSpacing": "0"
  },
  "label1": {
    "fontWeight": "500",
    "lineHeight": "24px",
    "fontSize": "16px",
    "letterSpacing": "0"
  },
  "label2": {
    "fontWeight": "500",
    "lineHeight": "20px",
    "fontSize": "14px",
    "letterSpacing": "0"
  },
  "label3": {
    "fontWeight": "500",
    "lineHeight": "16px",
    "fontSize": "12px",
    "letterSpacing": "0"
  },
  "caption1": {
    "fontWeight": "400",
    "lineHeight": "16px",
    "fontSize": "12px",
    "letterSpacing": "0"
  }
} as const;
